sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTR-52.pdf --upload --lsstdoc DMTR-52.tex --env=travis --ltd-product dmtr-52"
env:
  global:
    - secure: "gm/LUOHJd35/k5t4yvMywW+lYlRsWSmvVRv0hZCrmR/hv5XYG+kfBUeDiIoZVviaH694HkCNfLfiqa1rV/RxoEwcouFaXeTheNUbSjsxiusraP6AJ0NXrKc/qhWjOvtaTlf38XhQ04HdXRgCJ8s6f3LZshGnbGUNia7FCJ4W8EzfBT1VHbl/xaj4vMKPa2tkSbxbtjQYNylvgBmc4QXpeNDfMG8XGzQVwbW5adup3TDYoMGX0pRj0Ds0P4UKbHCISFLQUw0WuQa3Ff/28GlFfkbWVVOy8SZATVzrxJDfIL2zLkj0+0RN8QJ7FF2/vuWcBfxUUVcY2JVj45TtSj7c2XQEqnozsaHRGu6qAXlv2n3s7D9mvPNfEMpw5WUksGhJOgBsjsIU/B1zsT1BF221L1PpulMUf2d73Ys0YTE7Z6+Biqhz5X3fCCDR9VxOfRf2HMFPqR8kgC+cBc98XLlTkQlSByoqDe1HMNYeu55MV/f+0Q8z7WXyiwnXIky9JhcJ6b7IVqhS1JrRAC6BP48QY8WeFAk2tP1D1jd24w+QVWe4EgxDlhjc41Um1P+wcEFOuPuhLav4nh1w4XxQ3v/e9AZsFa/xnWdu/Zv3huSNQwkfc6Oie2qQR9QnJzdUfSMMiWVKS+zbcDXkrDLYDS1EcSdU4HrXnplMoGGWI6GisPI="
    - secure: "IlPvI55UC2qfy7rky5sflwOwtfWNJo6D/YDlagvyCMwAihDJ5XPphHxdfLJwHZnX1mX+ou8mHCu/6QRHi/kuBF8C9gUyXjpFpTjTOXOlhNHJ3YvQ4FBeFW1lBZCV4ZoRFBBxxXR8mj45X9v07d6j8jsW3XC5ZsSuI9VA//dfqD6AbikSqIKAHTFxKX/121WwUZo8qPHU8cHO7hwtKEWdidJcnk8fA5s83dCsio4BNbtY4jvSt6EOVMc4916ezEx7hbGqwha73UOSb8Ak8yY/F+meyoG+HpLveJc+vKkCQZstFCHaHxryl0jwA2hM3R96UNdLxYzCdXyMKuGDkrd8NKSxpPdUnOpHk3SvCp408IEocBhviWmleABl1UqDy690oCYpD3qh8U+n1EJA9CN63a28CdCcA+RmrViZX+M2SzVY/X05pIogyC4xDyvuiwWWCE3DNJpV9FsGOxA8GPY6Nk/I5+zwRjb8wdL0Ng/nGdYRynwhP8uYZgzx5roPtERhNcPsUHhOK7M/y7C/wiOi9crdiiX3h9Qp5vLjJQumgq23UK0BIJdMjcFst/MXlqZEyoa0hM/BevQFx0PQ09Et8chW2YCG0es8zNnB0F2fA2mRSfTKFfIA5PrbT5JzeWLd84unSx8gLEiyjZViYUcD7pVgx7pZiYF8WSd/nUeJ19I="
